name: Terraform Plan

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

defaults:
  run:
    working-directory: ./terraform/

jobs:
  terraform-plan:
    name: Terraform Lint, Scan, Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download terraform.tfvars from S3
        run: aws s3 cp s3://team-echo-ecs/terraform.tfvars ./

      - name: Verify terraform.tfvars exists
        run: test -f terraform.tfvars

      - name: List directory contents 
        run: ls -l

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: "latest"

      - name: Run TFLint
        run: tflint

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -input=false 


